### ISSUE TITLE
Color Overlay View

### ISSUE THREAD

**Issue by danieldesouzadev** [markormesher/android-fab#10]
Hi, is there any way to customize the background color when the menu is open? That is, that white with alpha?

Congratulations on the lib... tks!

**Comment by markormesher** [comment]
At the moment there isn't, but that wouldn't be too hard to add. I'll take a look at implementing it shortly. Thanks for the suggestion!

**Comment by danieldesouzadev** [comment]
Tks to your respond, I really need this implementation ...

**Comment by danieldesouzadev** [comment]
Uwoooo... only: 

In: FloatingActionButton: 

`public void setBackgroundCover(int colour) {
		savedBgCover = colour;
		coverView.setBackgroundColor(colour);
}`


`
private int savedBgCover =  0x99ffffff;

	@Override
	protected Parcelable onSaveInstanceState() {
		Bundle bundle = new Bundle();
		bundle.putBoolean("shown", shown);
		bundle.putInt("savedIconResId", savedIconResId);
		bundle.putInt("savedBgColour", savedBgColour);
		bundle.putInt("savedBgCover", savedBgCover);
		bundle.putParcelable("SUPER", super.onSaveInstanceState());
		return bundle;
	}`

**Comment by danieldesouzadev** [comment]
Thanks ... one question, if I synchronize the gradle in my project, do I get this update?

**Comment by markormesher** [comment]
You'll need to wait for me to do a release first, then update the version number. I'll comment here when it's done.

**Comment by danieldesouzadev** [comment]
I'm waiting ... congratulations ...

**Comment by danieldesouzadev** [comment]
If anyone needs it right away:

`fab.findViewById(uk.co.markormesher.android_fab.fab.R.id.cover).setBackgroundColor(0x99000000);`

**Comment by markormesher** [comment]
**^ That won't work properly.** It will change the colour, but you'll lose the radial expansion effect and get a square block of colour. You need to change the colour of the background drawable, which is a shape.

The new version has already been released. Change your Gradle dependency to version `1.3.2` and you'll get the new feature.

**Comment by danieldesouzadev** [comment]
It's perfect ... thank you ...

**Comment by markormesher** [comment]
No problem
