### ISSUE TITLE
Speed dial menu items stay drawn if rebuildSpeedDialMenu() is called when FAB is opened

### ISSUE THREAD

**Issue by tihomirleka** [markormesher/android-fab#12]
If speed dial menu is opened and `FloatingActionButton.rebuildSpeedDialMenu()` method is called currently rendered items are not destroyed and new set of speed dial items is created.

**Comment by markormesher** [comment]
Is this a major blocker for you? I'm going to be re-writing this whole project soonish anyway, but I try to find some time to patch the current version if it's essential.

**Comment by markormesher** [comment]
Fixed in v1.3.3.
