### ISSUE TITLE
Programmatically change expand direction

### ISSUE THREAD

**Issue by nvasilev0101** [markormesher/android-fab#13]
Currently the expand direction can be changed only in the xml with the expandDirection property. It would be very helpful if this property could be accessed programmatically.

**Comment by markormesher** [comment]
Hi @nvasilev0101. I haven't worked with this project in a while, but I'm fairly sure the direction can't actually be changed at all. If you take a look at #9 you can see a suggestion to implement this feature along with some code for doing so (not tested by me). It's on the board for the re-write coming some point this year, and it'll be accessible in XML and Java. I'm going to close this for now as I'm tracking the missing feature in #9.
