### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by SeaRoth** [markormesher/android-fab#19]
Why was FloatingActionButton chosen for the class name when Android has one with the same name? android.support.design.widget.FloatingActionButton

**Comment by markormesher** [comment]
Hey @SeaRoth. You make a good point - hindsight is a wonderful thing and a unique name probably would have been better! This code started out as a component of a commercial project, which is when the name was selected, and it was open-sourced some time later.

It's unlikely that someone would be using Android's FAB _and_ this one in the same project, so I'm not planning to rename everything, but if it's a causing a problem for you then you could create a "thin copy" of the library...

    uk.co.markormesher.android_fab.FloatingActionButton;

    public class CustomFloatingActionButton extends FloatingActionButton { }

...and then reference `CustomFloatingActionButton` throughout your codebase.
