### ISSUE TITLE
Method to set speed-dial buttons background color

### ISSUE THREAD

**Issue by Yahhi** [markormesher/android-fab#20]
I didn't find this on wiki, but it would be a good option if I can set not only icon but also background color for speed-dial buttons

**Comment by markormesher** [comment]
Hey @Yahhi. There's a method you can override in the speed-dial adapter called `getBackgroundColour` which will do what you're looking for. In v2.0.0 you'll find it [here](https://github.com/markormesher/android-fab/blob/development/fab/src/main/kotlin/uk/co/markormesher/android_fab/SpeedDialMenuAdapter.kt#L37) and in older versions it's [here](https://github.com/markormesher/android-fab/blob/0947d91172c1f42f977f6f80eeec0128a298bd1d/fab/src/main/java/uk/co/markormesher/android_fab/SpeedDialMenuAdapter.java#L31).
