### ISSUE TITLE
setOnSpeedMenuDialOpenListener() has wrong name

### ISSUE THREAD

**Issue by barbeau** [markormesher/android-fab#23]
With v2.0, code to set the open and close listener looks like this:

~~~
mLayersFab.setSpeedDialMenuAdapter(adapter);
mLayersFab.setOnSpeedMenuDialOpenListener(...);
mLayersFab.setOnSpeedDialMenuCloseListener(...);
~~~

The naming convention of the two set listeners methods are different:
* `setOnSpeedMenuDialOpenListener()`
* `setOnSpeedDialMenuCloseListener()`

Judging by the `setSpeedDialMenuAdapter()` method, it looks like the open listener method:

`setOnSpeedMenuDialOpenListener()`

should have been:

`setOnSpeedDialMenulOpenListener()`

**Comment by barbeau** [comment]
@markormesher Swapping the method name is obviously a breaking change, so I don't know how you want to handle this.

**Comment by markormesher** [comment]
Ha, wow, good spot. I think an alias is the best approach to fixing this, so we can move forwards with the right naming convention without breaking anything. I'll tag this issue in a commit shortly.

**Comment by markormesher** [comment]
@barbeau I'll be merging this and cutting a new release tonight. https://github.com/markormesher/android-fab/compare/fix-speed-dial-listener-naming-mistake

**Comment by barbeau** [comment]
Awesome, thanks!
