### ISSUE TITLE
Disappearing menu items when using v2 of library

### ISSUE THREAD

**Issue by barbeau** [markormesher/android-fab#25]
**Summary:** 

@markormesher I did a fairly straightforward port of our project to use v2 of this library - WIP PR at:
https://github.com/OneBusAway/onebusaway-android/pull/856

However, I'm seeing different behavior in terms of the visibility of menu items.  

If I tap on the "Bikeshare" menu item (see left screenshot below), the entire menu item disappears (see right screenshot below):

![image](https://user-images.githubusercontent.com/928045/35942761-c8941ae6-0c24-11e8-8d65-5d8e05aba4a3.png)

If I tap on the FAB twice (to close and re-open it) then the correct state is shown (i.e., after first tapping on the "Bikeshare" menu item, I would expect it to look like this instead of disappearing:

![image](https://user-images.githubusercontent.com/928045/35943375-c18a3c56-0c26-11e8-88cb-e46ad9989138.png)

Is there new behavior in v2 that I'm missing that's causing this?

**Steps to reproduce:** 

1. Clone and pull in WIP PR at https://github.com/OneBusAway/onebusaway-android/pull/856
1. Run `gradlew assembleObaGoogleDebug` or build [this build variant via Android Studio](https://github.com/OneBusAway/onebusaway-android#when-running-the-project-i-get-a-nullpointerexception-in-basemapfragment-related-to-mmap) 
1. Run app
1. Tap on hamburger menu
1. Tap on "Settings"
1. Tap on "Your region" and choose Tampa
1. Tap on "Layers" FAB button (top FAB in lower-right corner)
1. Tap on "Bikeshare" menu item

**Expected behavior:** 

"Bikeshare" menu item should stay visible and background should change from blue to gray, indicating that the layer is disabled

**Observed behavior:** 

"Bikeshare" menu item disappears

**Device and Android version:** 

Samsung Galaxy S8+ w/ Android 8.0 beta

**Comment by markormesher** [comment]
Hey, thanks for flagging this. Looks like should be a straightforward fix: the `rebuildSpeedDialMenu` method that you call in [this block](https://github.com/OneBusAway/onebusaway-android/blob/24e9ebd2dd9f034c45069ec18174c5c1911cd3a8/onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java#L1712-L1734) doesn't properly handle rebuilding the menu if it is still open. I'll take a look at this one tomorrow too!

**Comment by barbeau** [comment]
Awesome, thanks @markormesher! And thanks for the great library!

**Comment by markormesher** [comment]
https://github.com/markormesher/android-fab/compare/reposition-menu-items-when-rebuilt

Will be merged + released this afternoon

**Comment by markormesher** [comment]
Fixed in [v2.2.0](https://github.com/markormesher/android-fab/releases/tag/v2.2.0) 👍

**Comment by barbeau** [comment]
Thanks @markormesher!  I'll give it a try.

**Comment by barbeau** [comment]
@markormesher I only see v2.1.0 on JCenter:
https://bintray.com/markormesher/maven/android-fab

**Comment by markormesher** [comment]
My bad, should be published now: https://bintray.com/markormesher/maven/android-fab/v2.2.0
