### ISSUE TITLE
FloatingActionButton Ripple colour

### ISSUE THREAD

**Issue by ghost** [markormesher/android-fab#27]
Hi there

I'm having an issue, when I switched from the standard android FAB to this one my ripple effect on the FAB is no longer grey (or a darker orange), it now seems to use my primary colour of my application which is green, and on an orange FAB it really does not look right.

I set the FABs colour via `app:buttonBackgroundColour="@color/accent"` in the XML.

How would i go about changing this? I've tried setting the `cardViews` drawable to my own `selector ` which didn't work. Not sure what else to do.

This also happens on the `SpeedDialMenuItems `but the green isn't so bad on a grey background, though id prefer to use a darker grey then green too.

**UPDATE**
It is strange though when I press the FAB it does look like it goes grey or possibly a darker orange (which is great), but then suddenly tints a slight green.

**Comment by markormesher** [comment]
Hey @dkroukamp. Could you share an example of the code you're using? If it's in git, it would be super-useful to see how you were applying the styles before/after the change. Thanks.

**Comment by ghost** [comment]
Ill try getting a small example app up on here in a few hours for you to look at! Will Bump this thread when its up. Thanks alot :).

**Comment by ghost** [comment]
Figured out the issue while trying to replicate in a smaller project.

In my `styles.xml` I had `<item name="android:colorControlHighlight">@color/primary</item>` which applied the green highlight to all controls!

Sorry mate my mistake!

**Comment by markormesher** [comment]
No problem, glad you got it figured out! I should have time to release a new version for #26 some time this week.
