### ISSUE TITLE
Checking whether or not the SpeedDialMenu is open

### ISSUE THREAD

**Issue by ghost** [markormesher/android-fab#28]
Hey there again

I know there is a listener which we could use to set our own property to track whether or not the `SpeedDialMenu `is open, but it would be nice to have a simple getter for `speedDialMenuOpen` field instead so on methods like `onBackPressed` the `SpeedDialMenu ` can be closed via the back button too.

**Comment by markormesher** [comment]
Hey @dkroukamp, thanks for the suggestion. I completely agree that this would be a nice addition - I'll make sure it goes into the next release.

**Comment by markormesher** [comment]
Fixed in [v2.2.2](https://github.com/markormesher/android-fab/releases/tag/v2.2.2) - should be available on Bintray shortly.
