### ISSUE TITLE
impossible to assembleRelease

### ISSUE THREAD

**Issue by TurhanOz** [markormesher/android-fab#3]
Hi, 
assembleRelease of a project including this dependency is failing (error bellow).
Could you give some input on how to avoid this.
Cheers

Warning: uk.co.markormesher.android_fab.FloatingActionButton$$Lambda$1: can't find referenced class java.lang.invoke.LambdaForm$Hidden
Warning: uk.co.markormesher.android_fab.FloatingActionButton$$Lambda$4: can't find referenced class java.lang.invoke.LambdaForm$Hidden
Warning: uk.co.markormesher.android_fab.FloatingActionButton$$Lambda$5: can't find referenced class java.lang.invoke.LambdaForm$Hidden

**Comment by McPo** [comment]
Look at the proguard file.
https://github.com/markormesher/android-fab/blob/development/app/proguard-rules.pro

It seems, adding.

```
# hide warnings caused by Retrolamdba
-dontwarn java.lang.invoke.*
```

Was sufficient for it to be built.

**Comment by markormesher** [comment]
@TurhanOz I just added the FAB dependency to a completely blank Android project and it was able to compile and install correctly; the additional Proguard line suggested by @McPo shouldn't actually be necessary. Could you point me towards any of the relevant source code for the app causing the error and I'll take a closer look for you?

`build.gradle` for the blank application: https://gist.github.com/markormesher/128722e9890c6414f867759655bf1cb9

**Comment by McPo** [comment]
change minifyEnabled to true. I suspect that will reproduce the issue in
your app.

And ofcourse, make sure your building the release flavour.

**Comment by markormesher** [comment]
Building on the release flavour, of course. Enabling minify still threw up no issues. @TurhanOz,  did you have any luck following the suggestion above?

**Comment by TurhanOz** [comment]
Hi, 
the above proguard rule suggested by @McPo solved the issue :)
could you add this to the Readme @markormesher please ?
Cheers

**Comment by markormesher** [comment]
Interesting! I tried with a completely fresh IntelliJ/Gradle install this morning in a new VM and still had no issues. I'm going to leave this issue open until I can properly resolve this with a sure cause, but I will definitely add a note to the readme in the meantime.

Thanks for raising this @TurhanOz, and thanks for your input @McPo! :smile:

**Comment by markormesher** [comment]
The ProGuard rule does indeed seem to solve the issue - thank you so much for bringing it to my attention :smile: Something about my default setup must negate the issue; I added the plugin to a few other apps, some of which had the error (all of which were fixed with the ProGuard line).
