### ISSUE TITLE
Customize the menu

### ISSUE THREAD

**Issue by raveeshlawrance** [markormesher/android-fab#30]
Hi Writing this to know, how can i customize each row in menu item. I dont want to use the icons at right hand side, and the mehu text should have a background color, how can i implement this using your lib. could you please help me on this?

**Comment by markormesher** [comment]
Hey @boyhasnoname. If you check out the discussion on #24, you can see some code discussing adding a background to the menu text. There's no discussion of hiding the icons (which I wouldn't recommend anyway), but the `getIconWrapper()` method described [here](https://github.com/markormesher/android-fab#access-to-underlying-views) should let you hide/show the wrapper that the icon is placed into.

Let me know how it goes!

**Comment by raveeshlawrance** [comment]
Got it. Thanks a lot :)
