### ISSUE TITLE
XML Drawable not supported on all devices

### ISSUE THREAD

**Issue by ghost** [markormesher/android-fab#31]
Hello!
When I set FAB Icon using custom XML drawable not all devices were displaying icon.
Setting icon as normal png helped. I guess it should not work this way :D

**Comment by markormesher** [comment]
Hey @Cililing - thanks for reporting this. Could you give me an example of the code that wasn't working, and the devices that were having problems? The library is tested with XML drawables and I've just double-checked it now, and I wasn't able to repro the issue.

Under the hood, the icon is set as the background of a `LinearLayout` ([see here](https://github.com/markormesher/android-fab/blob/development/fab/src/main/kotlin/uk/co/markormesher/android_fab/FloatingActionButton.kt#L239)), so any kind of drawable _should_ work - if you can get an example that doesn't I'll try to find a way to resolve it 😃

**Comment by ghost** [comment]
Just creating icon with param drawable -> context.getDrawable(someXmlDrawableId). Sometime there was a icon, something wasn't. 
I don't know why, I had tried to found what was going wrong (including checking source code) and code was fine for me (i saw it was just background). Then I tried to use png drawable and everthing was fine.
I've tested it on Xiaomi Mi A1 (Oreo), Samsung S5 (I guess Marshmallow), LG Nexus (Oreo).

**Comment by markormesher** [comment]
Closing this as a stale issue, but feel free to re-open if a reliable reproduction can be found.
