### ISSUE TITLE
Not float up animation when snackbar shown

### ISSUE THREAD

**Issue by VladimirSlavic** [markormesher/android-fab#32]
It seems the floating button remains in position when a snackbar is being shown, whilst the native FAB implementation has it float up above the snackbar. Is there a way to get this to work with your implementation?

Thanks alot

**Comment by markormesher** [comment]
Hey @VladimirSlavic, thanks for pointing this out. I think the answer here is to make sure the FAB is inside a `CoordinatorLayout` and have the view implement a custom behaviour, something like [this](https://stackoverflow.com/a/35904421/3227795). You could try specifying like they do on that link, and I'll work on adding it to the next version of the library.

**Comment by markormesher** [comment]
Oops!

**Comment by markormesher** [comment]
Hey @VladimirSlavic - this should be fixed in [v2.3.0-rc1](https://github.com/markormesher/android-fab/releases/tag/v2.3.0-rc1). Let me know if there are any problems 👍

**Comment by VladimirSlavic** [comment]
I had already implemented my own behaviour, although i thought adding this to the library would make it much more desirable if it encapsulated the already default behaviour of the ordinary fab button. Your update works good though, very nice.
