### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by VladimirSlavic** [markormesher/android-fab#34]
Hey markormesher, 
I was wondering, is it possible to change the label color in the SpeedDialMenuItem? 

Regard, Vladimir

**Comment by markormesher** [comment]
Hey @VladimirSlavic! You should be able to do that with [this method](https://github.com/markormesher/android-fab/blob/development/fab/src/main/kotlin/uk/co/markormesher/android_fab/SpeedDialMenuAdapter.kt#L42-L46) in the speed-dial menu adapter. Feel free to reopen this if you have any problems.
