### ISSUE TITLE
Content cover doesn't cover whole screen

### ISSUE THREAD

**Issue by Yakow13** [markormesher/android-fab#35]
Device: Samsung SM-T580
Version android-fab: v2.2.2

On the tablet device, the cover keeps the left upper corner uncovered. My guess is, the circle which is used for animation has too small diameter. For more details, see the screenshot.

Thanks for your time :) 

![screenshot_20180620-163858](https://user-images.githubusercontent.com/10089252/41665673-cd426aba-74a8-11e8-9b76-94f78459f454.png)

**Comment by markormesher** [comment]
Hi Adam. Thanks for flagging this. I think you're right that the circle is
just a bit too small for that screen, and IIRC it's not sized dynamically
(obviously something that should be fixed!). I'm on holiday this week but
I'll try to take a look over the weekend.

**Comment by Yakow13** [comment]
Thanks for fast respond Mark.

Awesome :) . I would try it on my own and pull it, but wasn't able compile it in existing project, probably Kotlin vs. Java issue.

**Comment by markormesher** [comment]
This should be fixed now in v2.3.1
