### ISSUE TITLE
Unable to change icon in fab button programatically

### ISSUE THREAD

**Issue by VladimirSlavic** [markormesher/android-fab#36]
im trying to change the icon based on the page selected so for instance:
binding.fab.setButtonIconResource(R.drawable.profile_goto_arrow);
doesn't change the icon.

Any ideas?

**Comment by markormesher** [comment]
Hey @VladimirSlavic. Looks like that should work, and I just tested it on my device with no problems. Can you point me towards the repo where you have this code not working, or share a minimal example if it's not public?

**Comment by markormesher** [comment]
Closing as inactive. Feel free to reopen with a code example if you're still having problems.
