### ISSUE TITLE
how to change background color when click on fab?

### ISSUE THREAD

**Issue by mayank250004** [markormesher/android-fab#4]

**Comment by markormesher** [comment]
Do you want it to change to a new colour after the touch event, or to change to a new colour whilst being touched and then change back once released?

**Comment by markormesher** [comment]
@mayank250004 ?

**Comment by dasshuvajit** [comment]
```
    fab.setOnSpeedDialOpenListener(new FloatingActionButton.OnSpeedDialOpenListener() {
        @Override
        public void onOpen(FloatingActionButton v) {
            fab.setIcon(icons_2[iconSelected]);
            fab.setBackgroundColour(colours[colourSelected]);
        }
    });

    fab.setOnSpeedDialCloseListener(new FloatingActionButton.OnSpeedDialCloseListener() {
        @Override
        public void onClose(FloatingActionButton v) {
            fab.setIcon(icons[iconSelected]);
            fab.setBackgroundColour(colours_2[colourSelected]);
        }
    });
```

**Comment by markormesher** [comment]
@mayank250004 - The code that @Shuvajit-Das posted would work fine for swapping the icon and colour when the speed-dial menu opens and closes -- is this what you were looking for?

@Shuvajit-Das - Thank you for contributing!

@Both - If you're swapping the icons, make sure you leave [`rotateFab()`](https://github.com/markormesher/android-fab/blob/9fef3e711a579c08b8c8674db844923242b34c38/fab/src/main/java/uk/co/markormesher/android_fab/SpeedDialMenuAdapter.java#L51) returning `false`, otherwise things might look strange!

**Comment by markormesher** [comment]
I'm going to go ahead and close this -it's been three weeks since the question was raised, and a suitable answer has been provided. @Shuvajit-Das If you have any further issues, please feel free to re-open this issue or create a new one.

**Comment by pbasl** [comment]
Hi;
When I attempt the solution posted by @Shuvajit-Das I get an error "Cannot resolve symbol 'OnSpeedDialOpenListener'. 
Any suggestions?

**Comment by markormesher** [comment]
Hey @pbasl. What version of the library are you using? The code above is from v1.x, but if you're on v2.x you'll need to use the `SpeedDialMenuOpenListener` class (code: [class to override](https://github.com/markormesher/android-fab/blob/development/fab/src/main/kotlin/uk/co/markormesher/android_fab/SpeedDialMenuOpenListener.kt), [setter](https://github.com/markormesher/android-fab/blob/development/fab/src/main/kotlin/uk/co/markormesher/android_fab/FloatingActionButton.kt#L284-L286)).

**Comment by pbasl** [comment]
Thx @markormesher , that works
I am using v2.x
