### ISSUE TITLE
Release version 2.4.0 -- Failed to resolve

### ISSUE THREAD

**Issue by juanwall** [markormesher/android-fab#41]
Just FYI, when adding `implementation 'uk.co.markormesher:android-fab:2.4.0` to dependencies, I got a "Failed to resolve" error.

I checked the releases, and the 2.4.0 release appears to be mislabeled (along with the documentation).

I changed the dependency to `implementation 'uk.co.markormesher:android-fab:2.4.1`, and it resolved fine.

Thanks for this repo!

**Comment by markormesher** [comment]
Oops! 2.4.0 didn't publish properly so only 2.4.1 should be in use. I've fixed the release and the readme. Thanks for the heads up 👍
