### ISSUE TITLE
How to insert menu items in a speed dial adapter? I didnt find it in the documentation

### ISSUE THREAD

**Issue by edu1525** [markormesher/android-fab#42]

**Comment by markormesher** [comment]
Hi @edu1525. You'll need to implement an instance of `SpeedDialMenuAdapter` and set it on the FAB ([documented here](https://github.com/markormesher/android-fab#speed-dial-menu)). In that class you'll need to override the methods [documented here](https://github.com/markormesher/android-fab/blob/development/fab/src/main/kotlin/uk/co/markormesher/android_fab/SpeedDialMenuAdapter.kt). Feel free to reopen this issue if you run into any problems.
