### ISSUE TITLE
Request: Update android-support library to androidx

### ISSUE THREAD

**Issue by harytkon** [markormesher/android-fab#45]
**android-fab** uses currently old version of `android-support` package.
Any plans to update to **androidx**?

**Comment by Nimrodda** [comment]
I was wondering the same thing. We were thinking to integrate this library as well in our app, but I noticed that this library is not even using the latest support library version (28.0.0) before the change to AndroidX.

**Comment by markormesher** [comment]
Hey @harytkon @Nimrodda. Thanks for pointing this out - this library hasn't been touched in a few months and could definitely do with having some versions bumped. I'll try to get to it this week and publish an update soon.

**Comment by markormesher** [comment]
Just merged #46 - I'll be publishing 2.5.0 shortly.
