### ISSUE TITLE
Animation lag on SpeedDialMenu open/close while using with MaterialViewPager library

### ISSUE THREAD

**Issue by parasjain1** [markormesher/android-fab#5]
I'm experiencing significant lag or better say slow animation when opening/closing speed dial menu. I'm using MaterialViewPager library too.

**Comment by markormesher** [comment]
The MaterialViewPager library and this one shouldn't be interfering with each other - I just implemented both in a blank app and they both seemed to behave. Could you share the code (layout and Java) where you're using the FAB, please? I'll take a look and try to figure out what's happening.

**Comment by markormesher** [comment]
Looks like this has gone cold, so I'll close this issue. If you have any further problems, feel free to re-open.
