### ISSUE TITLE
CardView not round in KitKat

### ISSUE THREAD

**Issue by tihomirleka** [markormesher/android-fab#8]
Hi there, when library is used on small screen device with Android Jelly Bean (4.2.2) buttons are not circles. I tried to change width, height and radius of CardView but couldn't mange to get the circle. I'm thinking that maybe it's the drawable. I'm attaching the screenshot of your demo app so you understand better. As I said Android version is 4.2.2 and screen size is 320x480.

![screenshot_2017-04-24-16-28-33](https://cloud.githubusercontent.com/assets/448435/25347666/fcaf5c88-291b-11e7-99fd-36ffb0ec6ec9.png)

Cheers

**Comment by markormesher** [comment]
Thanks for flagging this, @tihomirleka. I was able to reproduce the problem on a virtual device, so it's definitely something I need to resolve.

Unfortunately I don't have a lot of time for personal projects at the moment (exams - yay!), so it may be a few weeks before this gets fixed. I'm making a note so I don't forget!

**Comment by markormesher** [comment]
I've just pushed a fix for this (v1.3.0) that replaces `CardView` with `ViewGroup` on SDK < 21 devices. I didn't want to take such an extreme measure, but it seemed to be the only way to reliably fix the issue on *all* devices. I'll close this now, but if there are any figure issues feel free to re-open or make a new issue (whichever is more appropriate).

**Comment by tihomirleka** [comment]
Hi, I tested the new version and visually it looks good (perfect circle), but there is another problem now. 
Anything "behind" the FAB is unclickable when speed dial menu is opened and closed by clicking the background (cover). If you open and close speed dial menu by clicking FAB everything works. 

The bug again appears only on small screen device on which I also discovered the initial bug (320x480, Android Jelly Bean 4.2.2). I created simple example (gist link is below) which you can copy/paste and below the link are steps to reproduce the bug.

https://gist.github.com/tihomirleka/2ef3b9fb2623fecfa89fa3eddc88a3ae

1. Click "Click me" button (toast shows)
2. Open speed dial menu
3. Close speed dial menu by clicking FAB again
4. Click "Click me" button (toast shows)
5. Open speed dial menu
6. Close speed dial menu by clicking on the cover (not FAB or one of menu items)
7. Click "Click me" button (not responding)

Let me know if you need any additional explanation.

Cheers

**Comment by markormesher** [comment]
Confirmed on a virtual device. I'm working on a different project this evening, but I will take a look over the weekend. Thanks again!

**Comment by markormesher** [comment]
Fixed in v1.3.1 :smile: 

(By the way, a full re-write of this project is coming soon!)

**Comment by tihomirleka** [comment]
I can confirm that this works now.

Cheers
